
package billingsoftwareproject;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-07-03T19:50:19.831+05:30
 * Generated source version: 2.7.5
 * 
 */
public final class BillingSoftwareProject_BillingSoftwareProjectPort_Client {

    private static final QName SERVICE_NAME = new QName("http://BillingSoftwareProject/", "BillingSoftwareProjectWS");

    private BillingSoftwareProject_BillingSoftwareProjectPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BillingSoftwareProjectWS.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BillingSoftwareProjectWS ss = new BillingSoftwareProjectWS(wsdlURL, SERVICE_NAME);
        BillingSoftwareProject port = ss.getBillingSoftwareProjectPort();  
        
        {
        System.out.println("Invoking menu...");
        billingsoftwareproject.Input _menu_parameters = new Input();
        Long value = 1l;
		_menu_parameters.setNumber1(value );	
        billingsoftwareproject.Output _menu__return = port.menu(_menu_parameters);
        System.out.println("menu.result=" + _menu__return);
        System.out.println("menu.result=" + _menu__return.getResult().getBurgher().getBurgherPrice());
        }

        System.exit(0);
    }
    
    public static BillingSoftwareProject BillingSoftwareProjectClient(){
    	URL wsdlURL = BillingSoftwareProjectWS.WSDL_LOCATION;
    	BillingSoftwareProjectWS ss = new BillingSoftwareProjectWS(wsdlURL, SERVICE_NAME);
        BillingSoftwareProject port = ss.getBillingSoftwareProjectPort(); 
        return port;
    }

}
