package billingsoftwareproject;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-07-03T19:50:20.020+05:30
 * Generated source version: 2.7.5
 * 
 */
@WebServiceClient(name = "BillingSoftwareProjectWS", 
                  wsdlLocation = "http://localhost:8080/BillingSoftwareProject/BillingSoftwareProjectPort?wsdl",
                  targetNamespace = "http://BillingSoftwareProject/") 
public class BillingSoftwareProjectWS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://BillingSoftwareProject/", "BillingSoftwareProjectWS");
    public final static QName BillingSoftwareProjectPort = new QName("http://BillingSoftwareProject/", "BillingSoftwareProjectPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/BillingSoftwareProject/BillingSoftwareProjectPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BillingSoftwareProjectWS.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/BillingSoftwareProject/BillingSoftwareProjectPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BillingSoftwareProjectWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BillingSoftwareProjectWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillingSoftwareProjectWS() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns BillingSoftwareProject
     */
    @WebEndpoint(name = "BillingSoftwareProjectPort")
    public BillingSoftwareProject getBillingSoftwareProjectPort() {
        return super.getPort(BillingSoftwareProjectPort, BillingSoftwareProject.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillingSoftwareProject
     */
    @WebEndpoint(name = "BillingSoftwareProjectPort")
    public BillingSoftwareProject getBillingSoftwareProjectPort(WebServiceFeature... features) {
        return super.getPort(BillingSoftwareProjectPort, BillingSoftwareProject.class, features);
    }

}
