package billingsoftwareproject;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-07-03T19:50:20.005+05:30
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://BillingSoftwareProject/", name = "BillingSoftwareProject")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BillingSoftwareProject {

    @WebResult(name = "Response", targetNamespace = "http://BillingSoftwareProject/", partName = "parameters")
    @Action(input = "http://BillingSoftwareProject/", output = "http://BillingSoftwareProject/BillingSoftwareProject/menuResponse")
    @WebMethod(action = "http://BillingSoftwareProject/")
    public Output menu(
        @WebParam(partName = "parameters", name = "Request", targetNamespace = "http://BillingSoftwareProject/")
        Input parameters
    );
}
