/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class clsJNI */

#ifndef _Included_clsJNI
#define _Included_clsJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     clsJNI
 * Method:    addTwoNumbers
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_clsJNI_addTwoNumbers
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
