<definitions
     targetNamespace="http://mywebservice/"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://mywebservice/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
     xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
     xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
    >
	<types>
		 <xsd:schema>
			 <xsd:import namespace="http://mywebservice/" schemaLocation="MyWebService.xsd"/>
		 </xsd:schema>
	</types>
	<message name ="request">
		<part name="parameters" element="tns:Request"/>
	</message>
	<message name ="response">
		<part name="parameters" element="tns:Response"/>
	</message>
	<portType name="MyWebService">
		<operation name="addition">
			<input message="tns:request"/>
			<output message="tns:response"/>
		</operation>
	</portType>
	<binding name="MyWebServicePortBinding" type="tns:MyWebService">
		<soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="addition">
			<soap12:operation soapAction="http://mywebservice/" soapActionRequired="false"/>
			<input>
				<soap12:body use="literal"/>
			</input>
			<output>
				<soap12:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="MyWebServiceWS">
		<port name="MyWebServicePort" binding="tns:MyWebServicePortBinding">
			<soap12:address location="http://localhost:7101/mywebservice-context-root/MyWebServiceWS"/>
		</port>
	</service>
</definitions>